

services:
  web:
    build: .
    volumes:
      - .:/app
      # Asegura que los estáticos se sincronicen fuera de la caja
      - ./staticfiles:/app/staticfiles 
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    restart: always