events { worker_connections 1024; }

http {
    server_of_tokens off;
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name hierroenlinea.com ://hierroenlinea.com;

        # Desafío de Certbot para validar que eres el dueño del dominio
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirección automática de HTTP a HTTPS seguro
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name hierroenlinea.com ://hierroenlinea.com;

        # Rutas de los certificados SSL que generará Certbot
        ssl_certificate /etc/letsencrypt/live/://hierroenlinea.com;
        ssl_certificate_key /etc/letsencrypt/live/://hierroenlinea.com;

        location / {
            proxy_pass http://web:8000; # Conecta el tráfico con Django dentro de Docker
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/static/; # Sirve los estilos CSS de forma ultra rápida
        }
    }
}