# Generated by Django 6.0.4 on 2026-04-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bcv_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('binance_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gap_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
