# Generated by Django 6.0.4 on 2026-05-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_rename_base_price_usd_product_cost_usd_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_cashea_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_cashea_base_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
